---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---

<!-- ```{r} -->
<!-- library(tidyverse) -->
<!-- library(RMySQL) -->

<!-- drv <- dbDriver("MySQL") -->

<!-- xdbsock <- "" -->

<!-- xdbuser <- Sys.getenv("MAS405_AWS_AM_DB_ROUSER_USER") -->
<!-- xpw     <- Sys.getenv("MAS405_AWS_AM_DB_ROUSER_PW") -->
<!-- xdbname <- Sys.getenv("MAS405_AWS_AM_DB_ROUSER_DBNAME") -->
<!-- xdbhost <- Sys.getenv("MAS405_AWS_AM_DB_ROUSER_HOST") -->
<!-- xdbport <- as.integer(Sys.getenv("MAS405_AWS_AM_DB_ROUSER_PORT")) -->

<!-- ### establish connection with Dave's DB -->

<!-- con <- dbConnect(drv, user=xdbuser, password=xpw, dbname=xdbname, host=xdbhost, port=xdbport, unix.sock=xdbsock) -->

<!-- ################## get info -->
<!-- dbListTables(con) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- imdb_boxOffice <- dbGetQuery(con, "SELECT * FROM imdb_boxOffice") -->
<!-- imdb_details <- dbGetQuery(con, "SELECT * FROM imdb_details") -->
<!-- imdb_top250_movies <- dbGetQuery(con, "SELECT * FROM imdb_top250_movies") -->
<!-- imdb_top250_shows <- dbGetQuery(con, "SELECT * FROM imdb_top250_shows") -->

<!-- dbDisconnect(con) -->

<!-- write.csv(imdb_boxOffice, "/Users/ajaypatel21/Desktop/STAT405_Data/Project/imdb_boxOffice.csv") -->
<!-- write.csv(imdb_details, "/Users/ajaypatel21/Desktop/STAT405_Data/Project/imdb_details.csv") -->
<!-- write.csv(imdb_top250_movies, "/Users/ajaypatel21/Desktop/STAT405_Data/Project/imdb_top250_movies.csv") -->
<!-- write.csv(imdb_top250_shows, "/Users/ajaypatel21/Desktop/STAT405_Data/Project/imdb_top250_shows.csv") -->
<!-- ``` -->


```{r}
library(tidyverse)
imdb_boxOffice <- read.csv("/Users/ajaypatel21/Desktop/STAT405_Data/Project/imdb_boxOffice.csv")
imdb_details <- read.csv("/Users/ajaypatel21/Desktop/STAT405_Data/Project/imdb_details.csv")
imdb_top250_movies <- read.csv("/Users/ajaypatel21/Desktop/STAT405_Data/Project/imdb_top250_movies.csv")
imdb_top250_shows <- read.csv("/Users/ajaypatel21/Desktop/STAT405_Data/Project/imdb_top250_shows.csv")
```


## Plot Summary - TF IDF and Most Common Words
```{r}
library(tm)
library(tidytext)

# Creating TF-IDF for the movie / show plots
tfidf <- imdb_details %>%
  select(X, id, fullTitle, type, year, imDbRating, plot) %>%
  unnest_tokens(word, plot) %>%
  group_by(X, id, fullTitle, type, year, imDbRating, word) %>%
  summarise(n = n()) %>%
  # count(fullTitle, word, sort = T) %>%
  anti_join(stop_words) %>%
  bind_tf_idf(word, fullTitle, n) %>%
  arrange(fullTitle, desc(n))

# Average TF-IDF score for each movie / show plot
temp <- tfidf %>%
  group_by(X, id, fullTitle, type, year, imDbRating) %>%
  summarise(avg_tf_idf = mean(tf_idf))

# Linear Regression - How well does plot TF-IDF predict rating
summary(lm(imDbRating ~ avg_tf_idf, temp))


# The 25 most frequent words in the movie plots and each word's average IMDB score
tfidf %>%
  filter(type == "Movie") %>%
  group_by(word) %>%
  summarise(n = n(),
            avg_rating = mean(imDbRating)) %>%
  slice_max(order_by = n, n = 25) %>%
  ggplot(aes(x = avg_rating, y = reorder(word, avg_rating), fill = avg_rating)) + geom_col(show.legend = F) + 
  labs(x = "Average Rating", y = "Word") + 
  ggtitle("25 Most Frequent Words in Movie Plots")

# The 25 most frequent words in the TV series plots and each word's average IMDB score
tfidf %>%
  filter(type == "TVSeries") %>%
  group_by(word) %>%
  summarise(n = n(),
            avg_rating = mean(imDbRating)) %>%
  slice_max(order_by = n, n = 25) %>%
  ggplot(aes(x = avg_rating, y = reorder(word, avg_rating), fill = avg_rating)) + geom_col(show.legend = F) + 
  labs(x = "Average Rating", y = "Word") + 
  ggtitle("25 Most Frequent Words in TV Series Plots")

# 10 most common words in movie / tv series plots, their frequency, and average rating
top10words <- tfidf %>%
  group_by(word) %>%
  summarise(n = n(),
            avg_rating = mean(imDbRating)) %>%
  slice_max(n, n = 10)

# Most common word and all plots where the word appeared
tfidf %>%
  filter(word %in% top10words$word[1]) %>%
  ggplot(aes(x = imDbRating, y = reorder(fullTitle, imDbRating), fill = word)) + 
  geom_col(show.legend = F)

```


## Genres and Relationship with IMDB Ratings
```{r}
# turning genres from genre column into dummy variables
temp <- imdb_details %>%
  select(X, id, fullTitle, type, year, imDbRating, genres) %>%
  unnest_tokens(word, genres, token = str_split, pattern = ", ") %>%
  group_by(X, id, fullTitle, type, year, imDbRating, word) %>%
  summarise(n = n()) %>%
  cast_sparse(fullTitle, word, n)

# combining imdb details data with dummy variables
data <- cbind(imdb_details %>% select(X, id, fullTitle, type, year, imDbRating, genres), data.frame(as.matrix(temp)))

## Linear Regression
# initial model with all genres
MASS::stepAIC(lm(imDbRating ~ comedy + drama + family + action + romance + adventure + sci.fi + biography + history + crime + mystery + thriller + fantasy + war + film.noir + western + musical + horror + music + animation + documentary + sport + game.show + reality.tv + news + short + talk.show, data), direction = "backward", trace = F)

# Final Regression Model after Backwards Selection - Note, this is the same as doing car::Anova
summary(lm(imDbRating ~ comedy + action + romance + adventure + sci.fi + biography + thriller + fantasy + animation + documentary, data))

## ANOVA
car::Anova(lm(imDbRating ~ comedy + action + romance + adventure + sci.fi + biography + thriller + fantasy + animation + documentary, data))
```


## Keywords and Relationship with IMDB Ratings
```{r}
# turning keywords / phrases from keywords column into dummy variables
temp <- imdb_details %>%
  select(X, id, fullTitle, type, year, imDbRating, keywords) %>%
  unnest_tokens(word, keywords, token = str_split, pattern = ",") %>%
  group_by(X, id, fullTitle, type, year, imDbRating, word) %>%
  summarise(n = n()) %>%
  cast_sparse(fullTitle, word, n)

# combining imdb details data with dummy variables
data <- cbind(imdb_details %>% select(imDbRating), data.frame(as.matrix(temp)))

# useless because there are 2114 keywords / phrases
summary(lm(imDbRating ~ ., data))

# going to use PCA to reduce dimensions, hopefully we can use PCs to describe relationship between keywords / phrases and imdb ratings
pc <- prcomp(data %>% select(-imDbRating))
variance_explained <- pc$sdev^2 / sum(pc$sdev^2)

qplot(c(1:4), variance_explained[1:4]) + 
  geom_line() + 
  xlab("Principal Component") + 
  ylab("Variance Explained") +
  ggtitle("Scree Plot") +
  ylim(0, 1)

# PCA did not help reduce dimensions, therefore, there probably is not a relationship between keywords / phrases and imdb score
```


## Clustering genres together into 2 groups - maybe the 2 groups represent movies and tv shows
```{r}
library(topicmodels)

# turning genres from genre column into dummy variables
temp <- imdb_details %>%
  select(X, id, fullTitle, type, year, imDbRating, genres) %>%
  unnest_tokens(word, genres, token = str_split, pattern = ", ") %>%
  group_by(X, id, fullTitle, type, year, imDbRating, word) %>%
  summarise(n = n()) %>%
  cast_sparse(fullTitle, word, n)

# beta is the probability the genre is generated from 1 of the 2 groups
library(reshape2)
lda <- tidy(LDA(temp, k = 2), matrix = "beta")

# getting the top 10 terms for each group 
top_terms <- lda %>%
  group_by(topic) %>%
  slice_max(beta, n = 10) %>% 
  ungroup() %>%
  arrange(topic, -beta)

top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()

lda %>%
  mutate(topic = paste0("topic", topic)) %>%
  pivot_wider(names_from = topic, values_from = beta) %>% 
  filter(topic1 > .001 | topic2 > .001) %>%
  mutate(log_ratio = log2(topic2 / topic1)) %>%
  ggplot(aes(x = log_ratio, y = reorder(term, log_ratio))) + geom_bar(stat = "identity")
```


## Clustering keywords together into groups - maybe each group can represent a different genre
```{r}
library(topicmodels)

# turning keywords / phrases from keywords column into dummy variables
temp <- imdb_details %>%
  select(X, id, fullTitle, type, year, imDbRating, keywords) %>%
  unnest_tokens(word, keywords, token = str_split, pattern = ",") %>%
  group_by(X, id, fullTitle, type, year, imDbRating, word) %>%
  summarise(n = n()) %>%
  cast_sparse(fullTitle, word, n)

# beta is the probability the genre is generated from 1 of the 2 groups
library(reshape2)
lda <- tidy(LDA(temp, k = 27), matrix = "beta")

# getting the top 5 terms for each group 
top_terms <- lda %>%
  group_by(topic) %>%
  slice_max(beta, n = 5) %>% 
  ungroup() %>%
  arrange(topic, -beta)

top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()

lda %>%
  mutate(topic = paste0("topic", topic)) %>%
  pivot_wider(names_from = topic, values_from = beta) %>% 
  filter(topic1 > .001 | topic2 > .001) %>%
  mutate(log_ratio = log2(topic2 / topic1)) %>%
  ggplot(aes(x = log_ratio, y = reorder(term, log_ratio))) + geom_bar(stat = "identity")


# genre_gamma <- tidy(LDA(temp, k = 27), matrix = "gamma")
# 
# genre_gamma %>%
#   mutate(document = reorder(document, gamma * topic)) %>%
#   ggplot(aes(factor(topic), gamma)) +
#   geom_boxplot() +
#   facet_wrap(~ document) +
#   labs(x = "topic", y = expression(gamma))
```







